name: Go

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: '40 1 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: go test -race ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v8.0.0
